name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      # Always include the checkout step so that 
      # your project is available for Godot to export
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Godot Export
      id: export
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v5.2.1
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2/Godot_v4.2-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2/Godot_v4.2-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true
        # Use the GitHub Actions workflow cache to cache the Godot export templates and Godot executable. 
        # Helps speed up builds by not having to download them every time.
        cache: true

      # This release action has worked well for me. However, you can most likely use any release action of your choosing.
      # https://github.com/ncipollo/release-action
    - name: Create release
      uses: ncipollo/release-action@v1.12.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ github.ref_name }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*
